Controllers/IncomeController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using MASdemo.Context;
using MASdemo.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using OfficeOpenXml;

namespace MASdemo.Controllers
{
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class IncomeController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public IncomeController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult RevenueDorm(int did)
        {
            if (HttpContext.Session.GetInt32("Oid") == null)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                int count = 0;
                var context = new masdatabaseContext();
                IQueryable<Dorm> sdorm = from q in context.Dorm where q.Oid == HttpContext.Session.GetInt32("Oid") select q;
                foreach (var t in sdorm)
                {
                    count = 1;
                }
                if (count == 0)
                {
                    return RedirectToAction("AddDorm", "Manage");
                }
                else if (count == 1)
                {
                    var myOid = HttpContext.Session.GetInt32("Oid");
                    ViewBag.myName = HttpContext.Session.GetString("Name");
                    ViewBag.Profile = HttpContext.Session.GetString("Picture");
                    ViewBag.did = did;
                    var monthfm = "";
                    string ConnectionStringMysql = "server=localhost;database=masdatabase;user=root;pwd=;sslmode=none";
                    MySqlConnection mysqlcon = new MySqlConnection(ConnectionStringMysql);
                    mysqlcon.Open();
                    string query = "SELECT SUM(c.Tatal_amount) as Amount, DATE_FORMAT(c.Date,'%M') as Month, DATE_FORMAT(c.Date,'%Y') as Year, d.DName as Name FROM owner o INNER JOIN dorm d ON d.OID = o.Oid INNER JOIN room r ON r.DID = d.DID INNER JOIN cal_info_room c ON c.RID = r.RID " +
                        "WHERE o.Oid = " + myOid + " AND d.DID = " + did + " GROUP BY c.Date";
                    MySqlCommand com = new MySqlCommand(query);
                    com.Connection = mysqlcon;
                    List<Income> incomes = new List<Income>();
                    MySqlDataReader reader = com.ExecuteReader();
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            if (reader["Month"].ToString() == "January")
                            {
                                monthfm = "1";
                            }
                            else if (reader["Month"].ToString() == "February")
                            {
                                monthfm = "2";
                            }
                            else if (reader["Month"].ToString() == "March")
                            {
                                monthfm = "3";
                            }
                            else if (reader["Month"].ToString() == "April")
                            {
                                monthfm = "4";
                            }
                            else if (reader["Month"].ToString() == "May")
                            {
                                monthfm = "5";
                            }
                            else if (reader["Month"].ToString() == "June")
                            {
                                monthfm = "6";
                            }
                            else if (reader["Month"].ToString() == "July")
                            {
                                monthfm = "7";
                            }
                            else if (reader["Month"].ToString() == "August")
                            {
                                monthfm = "8";
                            }
                            else if (reader["Month"].ToString() == "September")
                            {
                                monthfm = "9";
                            }
                            else if (reader["Month"].ToString() == "October")
                            {
                                monthfm = "10";
                            }
                            else if (reader["Month"].ToString() == "November")
                            {
                                monthfm = "11";
                            }
                            else if (reader["Month"].ToString() == "December")
                            {
                                monthfm = "12";
                            }

                            incomes.Add(new Income()
                            {
                                Month = monthfm,
                                Year = reader["Year"].ToString(),
                                Amount = reader["Amount"].ToString() + ","
                            });
                            ViewBag.DormName = reader["Name"];
                            ViewBag.GetIncome = incomes;
                        }
                    }
                    else
                    {
                        return RedirectToAction("Main", "Manage");
                    }
                    mysqlcon.Close();
                    mysqlcon.Open();
                    string queryall = "SELECT  DATE_FORMAT(c.Date, \"%M\") as Month,DATE_FORMAT(c.Date, \"%Y\") as Year,SUM(c.Tatal_amount) as Amount FROM owner o " +
                        "INNER JOIN dorm d ON d.OID = o.Oid " +
                        "INNER JOIN room r ON r.DID = d.DID " +
                        "INNER JOIN cal_info_room c ON c.RID = r.RID " +
                        "WHERE o.Oid = " + HttpContext.Session.GetInt32("Oid") + " AND d.DID = " + did + " " +
                        "GROUP BY c.Date ORDER BY c.Date DESC LIMIT 3";
                    MySqlCommand comall = new MySqlCommand(queryall);
                    comall.Connection = mysqlcon;
                    MySqlDataReader readerall = comall.ExecuteReader();
                    List<Last3Month> last3Months = new List<Last3Month>();
                    if (readerall.HasRows)
                    {
                        while (readerall.Read())
                        {
                            if (readerall["Month"].ToString() == "January")
                            {
                                monthfm = "มกราคม";
                            }
                            else if (readerall["Month"].ToString() == "February")
                            {
                                monthfm = "กุมภาพันธ์";
                            }
                            else if (readerall["Month"].ToString() == "March")
                            {
                                monthfm = "มีนาคม";
                            }
                            else if (readerall["Month"].ToString() == "April")
                            {
                                monthfm = "เมษายน";
                            }
                            else if (readerall["Month"].ToString() == "May")
                            {
                                monthfm = "พฤษภาคม";
                            }
                            else if (readerall["Month"].ToString() == "June")
                            {
                                monthfm = "มิถุนายน";
                            }
                            else if (readerall["Month"].ToString() == "July")
                            {
                                monthfm = "กรกฎาคม";
                            }
                            else if (readerall["Month"].ToString() == "August")
                            {
                                monthfm = "สิงหาคม";
                            }
                            else if (readerall["Month"].ToString() == "September")
                            {
                                monthfm = "กันยายน";
                            }
                            else if (readerall["Month"].ToString() == "October")
                            {
                                monthfm = "ตุลาคม";
                            }
                            else if (readerall["Month"].ToString() == "November")
                            {
                                monthfm = "พฤศจิกายน";
                            }
                            else if (readerall["Month"].ToString() == "December")
                            {
                                monthfm = "ธันวาคม";
                            }
                            last3Months.Add(new Last3Month()
                            {
                                Month = monthfm,
                                Year = readerall["Year"].ToString(),
                                Income = readerall.GetInt32(readerall.GetOrdinal("Amount"))
                            });
                        }
                    }
                    mysqlcon.Close();
                    ViewBag.Last3month = last3Months;
                }
                return View();
            }
        }

        public IActionResult Revenue()
        {
            if (HttpContext.Session.GetInt32("Oid") == null)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                ViewBag.myName = HttpContext.Session.GetString("Name");
                ViewBag.Profile = HttpContext.Session.GetString("Picture");
                var monthfm = "";
                int count = 0;
                var myOid = HttpContext.Session.GetInt32("Oid");
                var context = new masdatabaseContext();

Views/Shared/_Layout.cshtml
  
  
<!DOCTYPE html>  
<html>  
<head>  
    <meta charset="utf-8" />  
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
  
    <environment include="Development">  
  
        <link href="https://fonts.googleapis.com/css?family=Kanit:300" rel="stylesheet">  
        <link rel="stylesheet" href="~/vendors/iconfonts/mdi/css/materialdesignicons.min.css">  
        <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">  
        <link rel="stylesheet" href="~/vendors/css/vendor.bundle.addons.css">  
        <link rel="stylesheet" href="~/css/style.css">  
        <link rel="stylesheet" type="text/css" src="~/css/sweetalert2.min.css">  
        <link rel="shortcut icon" href="~/images/favicon.png" />  
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>  
    </environment>  
  
</head>  
<body>  
  
    <partial name="_CookieConsentPartial" />  
    <div class="container-scroller">  
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">  
  
  
            <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">  
                <a class="navbar-brand brand-logo" href="@Url.Action("Main", "Manage")">  
                    <img src="../images/logo.svg" alt="logo" />  
                </a>  
                <a class="navbar-brand brand-logo-mini" href="@Url.Action("Main", "Manage")">  
                    <img src="../images/logo-mini.svg" alt="logo" />  
                </a>  
            </div>  
            <div class="navbar-menu-wrapper d-flex align-items-center">  
                <ul class="navbar-nav navbar-nav-left header-links d-none d-md-flex"></ul>  
                <ul class="navbar-nav navbar-nav-right">  
  
                    <li class="nav-item dropdown d-none d-xl-inline-block">  
                        <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false"> 
                            <span class="profile-text">Hello, @ViewBag.myName</span> 
                            @if (ViewBag.Profile == "1") 
                            { 
                                <img class="img-xs rounded-circle" src="../images/faces-clipart/pic-4.png" alt="Profile image"> 
                            } 
                            else 
                            { 
                                <img class="img-xs rounded-circle" src="../uploads/img_profile/@ViewBag.Profile" alt="Profile image"> 
                            } 
                        </a>  
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">  
                            <a class="dropdown-item p-0">  
  
                            </a>  
                            <a class="dropdown-item mt-2" href="@Url.Action("EditProfile", "User")">  
                                แก้ไขข้อมูล  
                            </a>  
                            <a class="dropdown-item" href="@Url.Action("ChangePassword", "User")">  
                                เปลี่ยนรหัสผ่าน  
                            </a>  
  
                            <a class="dropdown-item" href="@Url.Action("Logout", "User")">  
                                ออกจากระบบ  
                            </a>  
                        </div>  
                    </li>  
                </ul>  
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">  
                    <span class="mdi mdi-menu"></span>  
                </button>  
            </div>  
        </nav>  
        <!-- partial -->  
        <div class="container-fluid page-body-wrapper">  
            <!-- partial:partials/_sidebar.html -->  
            <nav class="sidebar sidebar-offcanvas" id="sidebar">  
                <ul class="nav">  
                    <li class="nav-item">  
                        <a class="nav-link" asp-controller="Manage" asp-action="Main">  
                            <i class="menu-icon mdi mdi-home-account mdi-36px"></i>  
                            <span class="menu-title ml-4">หน้าแรก</span>  
                        </a>  
                    </li>  
                    <li class="nav-item">  
                        <a class="nav-link" asp-controller="Manage" asp-action="ManageDorm">  
                            <i class="menu-icon mdi mdi-city mdi-36px"></i>  
                            <span class="menu-title ml-4">จัดการหอ</span>  
                        </a>  
                    </li>  
                    <li class="nav-item">  
                        <a class="nav-link" asp-controller="Income" asp-action="Revenue">  
                            <i class="menu-icon mdi mdi-coin mdi-36px"></i>  
                            <span class="menu-title ml-4">รายได้ย้อนหลัง</span>  
                        </a>  
                    </li>   
                    <li class="nav-item">  
                        <a class="nav-link" asp-controller="User" asp-action="Report">  
                            <i class="menu-icon mdi mdi-comment-question-outline mdi-36px"></i>  
                            <span class="menu-title ml-4">รายงานปัญหา</span>  
                        </a>  
                    </li>  
  
  
  
                </ul>  
            </nav>  
            @RenderBody()  
  
        </div>  
        <environment include="Development">  
            <script src="~/js/used/sweetalert2.js"></script>  
            <script src="~/vendors/js/vendor.bundle.base.js"></script>  
            <script src="~/js/off-canvas.js"></script>  
            <script src="~/js/misc.js"></script>  
  
        </environment>  
        <environment exclude="Development">  
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"  
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"  
                    asp-fallback-test="window.jQuery"  
                    crossorigin="anonymous"  
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">  
            </script>  
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"  
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"  
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"  
                    crossorigin="anonymous"  
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">  
            </script>  
  
        </environment>  
  
        @RenderSection("Scripts", required: false)  
</body>  
</html>  

Views/Shared/_LayoutAdmin.cshtml
 
 
<!DOCTYPE html> 
<html> 
<head> 
    <meta charset="utf-8" /> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
 
    <environment include="Development"> 
 
        <link href="https://fonts.googleapis.com/css?family=Kanit:300" rel="stylesheet"> 
        <link rel="stylesheet" href="~/vendors/iconfonts/mdi/css/materialdesignicons.min.css"> 
        <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css"> 
        <link rel="stylesheet" href="~/vendors/css/vendor.bundle.addons.css"> 
        <link rel="stylesheet" href="~/css/style.css"> 
        <link rel="stylesheet" type="text/css" src="~/css/sweetalert2.min.css"> 
        <link rel="shortcut icon" href="~/images/favicon.png" /> 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
    </environment> 
 
</head> 
<body> 
 
    <partial name="_CookieConsentPartial" /> 
    <div class="container-scroller"> 
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row"> 
 
 
            <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center"> 
                <a class="navbar-brand brand-logo" href="@Url.Action("Main", "Manage")"> 
                    <img src="../images/logo.svg" alt="logo" /> 
                </a> 
                <a class="navbar-brand brand-logo-mini" href="@Url.Action("Main", "Manage")"> 
                    <img src="../images/logo-mini.svg" alt="logo" /> 
                </a> 
            </div> 
            <div class="navbar-menu-wrapper d-flex align-items-center"> 
                <ul class="navbar-nav navbar-nav-left header-links d-none d-md-flex"></ul> 
                <ul class="navbar-nav navbar-nav-right"> 
 
                    <li class="nav-item dropdown d-none d-xl-inline-block"> 
                        <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false"> 
                            <span class="profile-text">Hello, @ViewBag.myName</span> 
                            <img class="img-xs rounded-circle" src="~/images/faces-clipart/pic-4.png" alt="Profile image"> 
                        </a> 
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown"> 
                            <a class="dropdown-item p-0"> 
 
                            </a> 
 
                            <a class="dropdown-item" href="@Url.Action("Logout", "Admin")"> 
                                ออกจากระบบ 
                            </a> 
                        </div> 
                    </li> 
                </ul> 
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas"> 
                    <span class="mdi mdi-menu"></span> 
                </button> 
            </div> 
        </nav> 
        <!-- partial --> 
        <div class="container-fluid page-body-wrapper"> 
            <!-- partial:partials/_sidebar.html --> 
            <nav class="sidebar sidebar-offcanvas" id="sidebar"> 
                <ul class="nav"> 
                    <li class="nav-item"> 
                        <a class="nav-link" asp-controller="Admin" asp-action="Administrator"> 
                            <i class="menu-icon mdi mdi-home-account mdi-36px"></i> 
                            <span class="menu-title ml-4">หน้าแรก</span> 
                        </a> 
                    </li> 
                    <li class="nav-item"> 
                        <a class="nav-link" asp-controller="Admin" asp-action="CheckReport"> 
                            <i class="menu-icon mdi mdi-checkbox-multiple-blank-outline mdi-36px"></i> 
                            <span class="menu-title ml-4">เช็คปัญหา</span> 
                        </a> 
                    </li> 
                    <li class="nav-item"> 
                        <a class="nav-link" asp-controller="Admin" asp-action="Work"> 
                            <i class="menu-icon mdi mdi-checkbox-multiple-marked-outline mdi-36px"></i> 
                            <span class="menu-title ml-4">ปัญหาที่รับมา</span> 
                        </a> 
                    </li> 
                    <li class="nav-item"> 
                        <a class="nav-link" asp-controller="Admin" asp-action="Promotion"> 
                            <i class="menu-icon mdi mdi-approval mdi-36px"></i> 
                            <span class="menu-title ml-4">โปรโมชั่น</span> 
                        </a> 
                    </li> 
                    <li class="nav-item"> 
                        <a class="nav-link" asp-controller="Admin" asp-action="Announce"> 
                            <i class="menu-icon mdi mdi-message-bulleted mdi-36px"></i> 
                            <span class="menu-title ml-4">ประกาศ</span> 
                        </a> 
                    </li> 
 
 
                </ul> 
            </nav> 
            @RenderBody() 
 
        </div> 
        <environment include="Development"> 
            <script src="~/js/used/sweetalert2.js"></script> 
            <script src="~/vendors/js/vendor.bundle.base.js"></script> 
            <script src="~/js/off-canvas.js"></script> 
            <script src="~/js/misc.js"></script> 
 
        </environment> 
        <environment exclude="Development"> 
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js" 
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js" 
                    asp-fallback-test="window.jQuery" 
                    crossorigin="anonymous" 
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"> 
            </script> 
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js" 
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js" 
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" 
                    crossorigin="anonymous" 
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"> 
            </script> 
 
        </environment> 
 
        @RenderSection("Scripts", required: false) 
</body> 
</html> 

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <environment include="Development">
        
    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
	<link rel="stylesheet" type="text/css" href="~/vendors/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/iconfonts/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/iconic/css/material-design-iconic-font.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/animsition/css/animsition.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendors/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" type="text/css" src="~/css/sweetalert2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/mainLog.css">
 
         <link rel="shortcut icon" href="~/images/favicon.png" />
    </environment>
   
</head>
<body>
  
    <partial name="_CookieConsentPartial" />
     
        @RenderBody()
        
    <environment include="Development">

    <script src="~/js/sweetalert2.all.min.js"></script>
    <script src="~/js/sweetalert2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    <link href="https://fonts.googleapis.com/css?family=Kanit:300" rel="stylesheet">
	<script src="~/vendors/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendors/animsition/js/animsition.min.js"></script>
	<script src="~/vendors/bootstrap/js/popper.js"></script>
	<script src="~/vendors/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendors/select2/select2.min.js"></script>
	<script src="~/vendors/daterangepicker/moment.min.js"></script>
	<script src="~/vendors/daterangepicker/daterangepicker.js"></script>
	<script src="~/vendors/countdowntime/countdowntime.js"></script>
	<script src="~/js/main.js"></script>


    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
     
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>